config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  root to: 'home#index'

  resources :destinations
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :items
  belongs_to :user

  def queue
    items.where(status: 'wait').reverse
  end

  def sent_list
    items.where(status: 'sent')
  end

  def get_last_from_queue
    queue.last
  end

  def page_token
    data = user.get_page_token(fb_page)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :source, ImageUploader
  belongs_to :destination
end

app/models/user.rb
class User < ApplicationRecord
  has_many :destinations

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      # user.image = auth.info.image
      user.token = auth.credentials.token
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def page_list
    get_pages_data.map { |page| page['name'] }
  end

  def get_page_token(page_name)
    page = get_pages_data.find { |page| page['name'] == page_name }
    page['access_token']
  end

  private

  def get_pages_data
    @graph = Koala::Facebook::API.new(token)
    @graph.get_connections('me', 'accounts')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    destinations_path
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy, :add_items]

  def index
    @destination = Destination.new
    @destinations = Destination.all
  end

  def show
  end

  def new
    @destination = Destination.new
  end

  def edit
    @pages = @destination.user.page_list
  end

  def create
    @destination = Destination.new(destination_params)
    @destination.user = current_user
    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_destination
    @destination = Destination.find(params[:id])
  end

  def destination_params
    params.require(:destination).permit(:name, :user_id, :item_id, :fb_page)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      if current_user.destinations.count == 1
        redirect_to destination_path(current_user.destinations.first)
      else
        redirect_to destinations_path
      end
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = Item.new(item_params)
    @item.status = 'wait'
    respond_to do |format|
      if @item.save
        format.js { }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.js { }
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :source, :destination_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_integration_helper.rb
module CheckIntegrationHelper
  def check_integration(destination)
    destination.fb_page?
  end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/edit.erb
<div class="col-md-2">
  <%= link_to 'Back', destination_path(@destination), class: 'btn btn-default' %>
</div>

<div class="col-md-4 col-md-offset-2 text-center">
  <%= simple_form_for @destination, html: { class: 'form-horizontal' },
                                    wrapper: :horizontal_form do |f| %>
    <%= f.input :name %>
    <%= f.input :fb_page, collection: @pages %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/destinations/index.erb
<div class="row">
  <div class="col-md-2">
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#new-destination-modal" id="new-destination">
      New destination
    </button>
  </div>

  <div class="col-md-8 text-center">
    <h2>My destinations</h2>
  </div>
</div>

<hr>

<div class="row">
  <% @destinations.each do |destination| %>
    <div class="destination-index col-md-2">
      <%= link_to destination_path(destination) do %>
        <div class="destination-index__name">
          <%= destination.name %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<!-- Modal -->
<div class="modal fade" id="new-destination-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Destination</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @destination do |f| %>
          <%= f.input :name %>
          <%= f.button :submit, class: "center-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/destinations/new.erb
<%= simple_form_for @destination do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/destinations/show.erb
<div class="row">
  <div class="col-md-2">
    <%= link_to 'Back', destinations_path, class: 'btn btn-default' %>
  </div>

  <div class="col-md-8 text-center">
    <h1>[ <%= @destination.name %> ]</h1>
    <b>fb:</b> <span class="bullet <%= check_integration(@destination) ? 'green' : 'red' %>">&bull;</span>
  </div>

  <div class="pull-right">
    <%= link_to 'Edit', edit_destination_path(@destination.id), class: 'btn btn-default' %>
  </div>
</div>

<hr>

<div class="new-items">
  <%= form_for Item.new do |f|%>
    <%= f.hidden_field :destination_id, value: @destination.id %>
    <div class="upload center-block">
      <%= f.file_field :source, multiple: true, name: 'item[source]', id: 'files-upload'%>
    </div>
  <% end %>

  <div class="progress">
    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
    </div>
  </div>
</div>

<hr>

<!-- Nav tabs -->
<ul class="nav nav-tabs nav-justified" role="tablist">
  <li role="presentation" class="active"><a href="#queue" aria-controls="queue" role="tab" data-toggle="tab">Queue (<%= @destination.queue.count %>)</a></li>
  <li role="presentation"><a href="#sent" aria-controls="sent" role="tab" data-toggle="tab">Sent (<%= @destination.sent_list.count %>)</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div role="tabpanel" class="tab-pane fade in active" id="queue">
    <div class="items queue row">
      <% @destination.queue.each do |item| %>
        <div class="item col-xs-3 text-center" id="item-<%= item.id %>">
          <%= image_tag item.source, class: 'img-responsive' %>
          <%= link_to item, method: :delete, remote: true do %>
            <%= fa_icon 'trash fw 2x', 'item-id': item.id %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div role="tabpanel" class="tab-pane fade" id="sent">
    <div class="items row">
      <% @destination.sent_list.each do |item| %>
        <div class="item col-xs-3 text-center" id="item-<%= item.id %>">
          <%= image_tag item.source, class: 'img-responsive' %>
          <%= link_to item, method: :delete, remote: true do %>
            <%= fa_icon 'trash fw 2x', 'item-id': item.id %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.erb
<h1 class="text-center"> Witaj </h1>

app/views/items/_item.erb
<div class="item col-xs-3 text-center" id="item-<%= item.id %>">
  <%= image_tag item.source, class: 'img-responsive' %>
  <%= link_to item, method: :delete, remote: true do %>
    <%= fa_icon 'trash fw 2x', 'item-id': item.id %>
  <% end %>
</div>

app/views/items/create.js.erb
$('.items.queue').prepend("<%= j render(@item) %>");

app/views/items/destroy.js.erb
$('#item-<%= @item.id %>').remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sent</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Sent</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to 'Destinations', destinations_path %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.name %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li> <%= link_to "Sign in with fb", user_facebook_omniauth_authorize_path %> </li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>